/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author User
 */
public class kamar extends javax.swing.JFrame {
    
     private Connection conn = new koneksi().connect();
  private DefaultTableModel tabmode;
    /**
     * Creates new form kamar
     */
    public kamar() {
        initComponents();
         kosong();
        aktif();
        datatable();
        clearcb();
        bgroup.add(ready);
        bgroup.add(nready);
    }
    
    private void clearcb() {
    cbwf.setSelected(false);
    cbtv.setSelected(false);
    cbsb.setSelected(false);
    cbdb.setSelected(false);
    cbtb.setSelected(false);
    cbbr.setSelected(false);
    cbklks.setSelected(false);
    cbblkn.setSelected(false);
    cbbtl.setSelected(false);
    cbsmkng.setSelected(false);
}
 protected void aktif(){
        kdkmr.requestFocus();
    }

    protected void kosong(){
        kdkmr.setText("");
        tpkmr.setText("");
        kapas.setText("");
        lantai.setSelectedIndex(0);
        txtcari.setText("");
        clearcb();
        harga.setText("");
        bgroup.clearSelection();
    }
    protected void datatable(){
        Object[] Baris = {"Kode Kamar", "Tipe Kamar", "Kapasitas"
                , "Lantai", "Fasilitas", "Harga Per-malam","Status"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();
         try {
            String sql = "SELECT * FROM kamar where kode like '%" + cariitem +
                    "%' or tipe like '%" + cariitem + "%' order by kode asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7)
                });
            }
            tblhotel.setModel(tabmode);
         }catch (Exception e){
             JOptionPane.showMessageDialog(null,"data gagal di panggil" +e);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tpkmr = new java.awt.TextField();
        kapas = new java.awt.TextField();
        kdkmr = new java.awt.TextField();
        lantai = new javax.swing.JComboBox<>();
        cbwf = new javax.swing.JCheckBox();
        cbtv = new javax.swing.JCheckBox();
        cbsb = new javax.swing.JCheckBox();
        cbdb = new javax.swing.JCheckBox();
        cbtb = new javax.swing.JCheckBox();
        cbbr = new javax.swing.JCheckBox();
        cbklks = new javax.swing.JCheckBox();
        cbblkn = new javax.swing.JCheckBox();
        cbbtl = new javax.swing.JCheckBox();
        cbsmkng = new javax.swing.JCheckBox();
        harga = new java.awt.TextField();
        save = new java.awt.Button();
        ubah = new java.awt.Button();
        batal = new java.awt.Button();
        bkeluar = new java.awt.Button();
        txtcari = new java.awt.TextField();
        cari = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhotel = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        ready = new javax.swing.JRadioButton();
        nready = new javax.swing.JRadioButton();
        hapus = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 13, 148));

        jLabel1.setBackground(java.awt.Color.cyan);
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mochammad Wildan");

        jLabel2.setBackground(java.awt.Color.cyan);
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("202343501453");

        jLabel3.setBackground(java.awt.Color.cyan);
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("R6R");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("KODE KAMAR");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("TIPE KAMAR");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("KAPASITAS");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("LANTAI");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("FASILITAS");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("HARGA PER-MALAM");

        tpkmr.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tpkmr.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tpkmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpkmrActionPerformed(evt);
            }
        });

        kapas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kapas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapasActionPerformed(evt);
            }
        });

        kdkmr.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kdkmr.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kdkmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdkmrActionPerformed(evt);
            }
        });

        lantai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cbwf.setText("Free Wifi");

        cbtv.setText("Smart TV");

        cbsb.setText("Single Bed");

        cbdb.setText("Double Bed");

        cbtb.setText("Twin Bed");

        cbbr.setText("Breakfast");

        cbklks.setText("Kulkas");

        cbblkn.setText("Balkon");

        cbbtl.setText("Batal Reservasi");

        cbsmkng.setText("Smoking");

        harga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        harga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        save.setLabel("Save");
        save.setName(""); // NOI18N
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        ubah.setActionCommand("Ubah");
        ubah.setLabel("Ubah");
        ubah.setName(""); // NOI18N
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        batal.setActionCommand("Batal");
        batal.setLabel("Batal");
        batal.setName(""); // NOI18N
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        bkeluar.setActionCommand("Batal");
        bkeluar.setLabel("Keluar");
        bkeluar.setName(""); // NOI18N
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        txtcari.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        cari.setActionCommand("Batal");
        cari.setLabel("Cari");
        cari.setName(""); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        tblhotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblhotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhotelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhotel);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setText("STATUS");

        ready.setText("TERSEDIA");

        nready.setText("TIDAK TERSEDIA");

        hapus.setActionCommand("Hapus");
        hapus.setLabel("Hapus");
        hapus.setName(""); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kapas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tpkmr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kdkmr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lantai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbwf)
                                    .addComponent(cbtv)
                                    .addComponent(cbsb)
                                    .addComponent(cbdb)
                                    .addComponent(cbtb))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbsmkng)
                                    .addComponent(cbbtl)
                                    .addComponent(cbblkn)
                                    .addComponent(cbklks)
                                    .addComponent(cbbr)))
                            .addComponent(ready)
                            .addComponent(nready)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(kdkmr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tpkmr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(kapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbwf)
                    .addComponent(cbbr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbtv)
                    .addComponent(cbklks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbsb)
                    .addComponent(cbblkn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdb)
                    .addComponent(cbbtl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbtb)
                    .addComponent(cbsmkng))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ready))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nready)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
        );

        bkeluar.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpkmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpkmrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpkmrActionPerformed

    private void kapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kapasActionPerformed

    private void kdkmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdkmrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdkmrActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
    kosong();
    datatable();
    }//GEN-LAST:event_batalActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
 String lnt = lantai.getSelectedItem().toString();
        String stts = null;
      if (ready.isSelected()){
          stts = "Ready";
      } else if (nready.isSelected()){
          stts = "Tidak Ready";
      }
      java.util.ArrayList<String> fasilitasDipilih = new java.util.ArrayList<>();
    if (cbwf.isSelected())     fasilitasDipilih.add("WiFi");
    if (cbtv.isSelected())     fasilitasDipilih.add("Smart TV");
    if (cbsb.isSelected())     fasilitasDipilih.add("Single Bed");
    if (cbdb.isSelected())     fasilitasDipilih.add("Double Bed");
    if (cbtb.isSelected())     fasilitasDipilih.add("Twin Bed");
    if (cbbr.isSelected())     fasilitasDipilih.add("Breakfast");
    if (cbklks.isSelected())   fasilitasDipilih.add("Kulkas");
    if (cbblkn.isSelected())   fasilitasDipilih.add("Balkon");
    if (cbbtl.isSelected())    fasilitasDipilih.add("Batal Reservasi");
    if (cbsmkng.isSelected())  fasilitasDipilih.add("Smoking Area");
    
    String fasilitas = String.join(", ", fasilitasDipilih);
      String sql = " insert into kamar values (?,?,?,?,?,?,?)";
         try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, kdkmr.getText());
            stat.setString(2, tpkmr.getText());
            stat.setString(3, kapas.getText());
            stat.setString(4, lnt);
            stat.setString(5, fasilitas);
            stat.setString(6, harga.getText());
            stat.setString(7, stts);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            aktif();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan " + e);
        } 
         datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
    String lnt = lantai.getSelectedItem().toString();
        String stts = null;
      if (ready.isSelected()){
          stts = "Ready";
      } else if (nready.isSelected()){
          stts = "Tidak Ready";
      }
      java.util.ArrayList<String> fasilitasDipilih = new java.util.ArrayList<>();
    if (cbwf.isSelected())     fasilitasDipilih.add("WiFi");
    if (cbtv.isSelected())     fasilitasDipilih.add("Smart TV");
    if (cbsb.isSelected())     fasilitasDipilih.add("Single Bed");
    if (cbdb.isSelected())     fasilitasDipilih.add("Double Bed");
    if (cbtb.isSelected())     fasilitasDipilih.add("Twin Bed");
    if (cbbr.isSelected())     fasilitasDipilih.add("Breakfast");
    if (cbklks.isSelected())   fasilitasDipilih.add("Kulkas");
    if (cbblkn.isSelected())   fasilitasDipilih.add("Balkon");
    if (cbbtl.isSelected())    fasilitasDipilih.add("Batal Reservasi");
    if (cbsmkng.isSelected())  fasilitasDipilih.add("Smoking Area");
    
    String fasilitas = String.join("", fasilitasDipilih);
      String sql = "update kamar set tipe=?, kpsts=?, lantai=?, facll=?,hrg_pmlm=?, status=? where kode=?";
         try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tpkmr.getText());
            stat.setString(2, kapas.getText());
            stat.setString(3, lnt);
            stat.setString(4, fasilitas);
            stat.setString(5, harga.getText());
            stat.setString(6, stts);
            stat.setString(7, kdkmr.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil di Ubah");
            kosong();
            aktif();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal di ubah " + e);
        } 
         datatable();  
    }//GEN-LAST:event_ubahActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    int ok = JOptionPane.showConfirmDialog(null, "hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                String sql = "delete from kamar where kode ='" + kdkmr.getText() + "'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                aktif();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus " + e);
            }
            datatable();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
    if (evt.getKeyCode()== KeyEvent.VK_ENTER){
           datatable();
    }
    }//GEN-LAST:event_txtcariKeyPressed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
    datatable();
    }//GEN-LAST:event_cariActionPerformed

    private void tblhotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhotelMouseClicked
    int bar = tblhotel.getSelectedRow();
String a = tabmode.getValueAt(bar, 0).toString();
String b = tabmode.getValueAt(bar, 1).toString();
String c = tabmode.getValueAt(bar, 2).toString();
String d = tabmode.getValueAt(bar, 3).toString();
String e = tabmode.getValueAt(bar, 4).toString();
String f = tabmode.getValueAt(bar, 5).toString();
String g = tabmode.getValueAt(bar, 6).toString();

kdkmr.setText(a);
tpkmr.setText(b);
kapas.setText(c);
lantai.setSelectedItem(d);
if (e.contains("WiFi"))         cbwf.setSelected(true);
    if (e.contains("TV"))           cbtv.setSelected(true);
    if (e.contains("Sarapan"))      cbsb.setSelected(true);
    if (e.contains("Double Bed"))   cbdb.setSelected(true);
    if (e.contains("Twin Bed"))     cbtb.setSelected(true);
    if (e.contains("Brankas"))      cbbr.setSelected(true);
    if (e.contains("Kulkas"))       cbklks.setSelected(true);
    if (e.contains("Balkon"))       cbblkn.setSelected(true);
    if (e.contains("Bathtub"))      cbbtl.setSelected(true);
    if (e.contains("Smoking Area")) cbsmkng.setSelected(true);
harga.setText(f);
 if ("Ready".equals(g)){
          ready.setSelected(true);
      } else{
          nready.setSelected(true);
      }
    }//GEN-LAST:event_tblhotelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button batal;
    private javax.swing.ButtonGroup bgroup;
    private java.awt.Button bkeluar;
    private java.awt.Button cari;
    private javax.swing.JCheckBox cbblkn;
    private javax.swing.JCheckBox cbbr;
    private javax.swing.JCheckBox cbbtl;
    private javax.swing.JCheckBox cbdb;
    private javax.swing.JCheckBox cbklks;
    private javax.swing.JCheckBox cbsb;
    private javax.swing.JCheckBox cbsmkng;
    private javax.swing.JCheckBox cbtb;
    private javax.swing.JCheckBox cbtv;
    private javax.swing.JCheckBox cbwf;
    private java.awt.Button hapus;
    private java.awt.TextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextField kapas;
    private java.awt.TextField kdkmr;
    private javax.swing.JComboBox<String> lantai;
    private javax.swing.JRadioButton nready;
    private javax.swing.JRadioButton ready;
    private java.awt.Button save;
    private javax.swing.JTable tblhotel;
    private java.awt.TextField tpkmr;
    private java.awt.TextField txtcari;
    private java.awt.Button ubah;
    // End of variables declaration//GEN-END:variables
}
